### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [18kazee/drummer-tracker#97]
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## READMEから課題解決する実装がされているか&動いている
挙動確認しました。アーティストの検索ができることを確認しました。

## 静的コードチェックが入っている
・app/mailers/user_mailer.rb：インデントが崩れている箇所がありそうだったので確認しましょう。
・Gemfileの余計な記載も削除しておきましょう。（最下部の「group :production do...」）

## 就活において十分な技術力を示せる機能を実装しているか
・`set_posts`メソッド・`set_post`メソッドはbefore_actionで呼び出したほうが良いかと思います。
・使用していないhelperファイルなどは削除しておきましょう。
・app/controllers/recommended_drummers_controller.rbの`select_user_genres`内の分岐などは、Choiceモデルにインスタンスメソッドとして切り出した方がFat Controllerの解消に繋げられそうです。

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
・MVPリリース時点としては問題ないように思いました。
・各アーティストのカード（開示版）には、文字情報しか無いため、一覧等で見た際にも興味や関心を引かせる工夫があると良いように感じました。
![スクリーンショット 2023-08-14 12 38 21](https://github.com/18kazee/drummer-tracker/assets/61481161/b59b5e57-d099-444d-960e-8d3b43eb55d0)
・診断の結果のページもカードが縦に３つ並んでいる印象を受けたので、レスポンシブ対応＆診断結果からそのアーティスト情報をクリックさせる工夫があると良いように感じました。
・「おすすめなドラマーを投稿」画面ですが、もう少し交流しやすいようにチャット化しても良いように感じました。

```
■チャット機能
概要：FacebookメッセンジャーやSNSなどには、チャット機能が必ずついています。現在では、WebSocketを用いることで、リアルタイムでやり取りが可能となっています。コツさえ掴めば、比較的簡単に実装できます。ダイレクトメッセージのようなチャット機能を実装することで、ユーザー同士のコミュニケーションを活性化させることができるかもしれません。

使用技術・ライブラリ：
- WebSocket
  - https://ja.wikipedia.org/wiki/WebSocket
- ActionCable（Rails標準）
  - https://railsguides.jp/action_cable_overview.html
```

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
https://github.com/18kazee/drummer-tracker/issues/96 も拝見しました。
良さそうなので上記質問等への回答と対応をお願いします。

**Comment by Tsuchiya2** [comment]
@18kazee 
ご返信無いようですが、独自ドメインを取得して反映しておきましょう。

**Comment by 18kazee** [comment]
@Tsuchiya2 
大変遅くなりまして申し訳ありません。

ご確認いただきましてありがとうございます！
本リリースは変わらず8月末を目処に行えるよう開発します。
それまでにレビューいただいた機能の機能を完成させていきます。
また、独自ドメインの設定も承知いたしました！
ありがとうございます！

**Comment by Tsuchiya2** [comment]
ご返信ありがとうございます。
引き続き開発頑張ってください！
